
@base_address = http://localhost:3000/api/people

GET {{base_address}}
Content-Type: application/json

###
POST {{base_address}}
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Paul"
}

###
GET {{base_address}}/2
Content-Type: application/json


###
PUT {{base_address}}/3
Content-Type: application/json

{
    "personId":3,
    "firstName":"Jannet",
    "lastName":"Radley"
}


###
DELETE {{base_address}}/3
Content-Type: application/json
